//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.8009.
// 
namespace prjColetorDadosCSNet35.WebService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServicoBancoDadosSoap", Namespace="http://tempuri.org/")]
    public partial class WebServicoBancoDados : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public WebServicoBancoDados() {
            this.Url = "http://srvpatrimonio/Todos/WebServicoBancoDados.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdGerarNumeroIdentificacao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int mtdGerarNumeroIdentificacao() {
            object[] results = this.Invoke("mtdGerarNumeroIdentificacao", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdGerarNumeroIdentificacao(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdGerarNumeroIdentificacao", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public int EndmtdGerarNumeroIdentificacao(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndHelloWorld(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdObterNumeroIdentificacao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int mtdObterNumeroIdentificacao() {
            object[] results = this.Invoke("mtdObterNumeroIdentificacao", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdObterNumeroIdentificacao(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdObterNumeroIdentificacao", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public int EndmtdObterNumeroIdentificacao(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdResetarContadorTabelaBensEletronorteMobile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void mtdResetarContadorTabelaBensEletronorteMobile(int NumeroIdentificacao) {
            this.Invoke("mtdResetarContadorTabelaBensEletronorteMobile", new object[] {
                        NumeroIdentificacao});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdResetarContadorTabelaBensEletronorteMobile(int NumeroIdentificacao, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdResetarContadorTabelaBensEletronorteMobile", new object[] {
                        NumeroIdentificacao}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndmtdResetarContadorTabelaBensEletronorteMobile(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdResetarContadorTabelaCentroCustoMobile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void mtdResetarContadorTabelaCentroCustoMobile(int NumeroIdentificacao) {
            this.Invoke("mtdResetarContadorTabelaCentroCustoMobile", new object[] {
                        NumeroIdentificacao});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdResetarContadorTabelaCentroCustoMobile(int NumeroIdentificacao, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdResetarContadorTabelaCentroCustoMobile", new object[] {
                        NumeroIdentificacao}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndmtdResetarContadorTabelaCentroCustoMobile(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdResetarContadorTabelaEmpregadosMobile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void mtdResetarContadorTabelaEmpregadosMobile(int NumeroIdentificacao) {
            this.Invoke("mtdResetarContadorTabelaEmpregadosMobile", new object[] {
                        NumeroIdentificacao});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdResetarContadorTabelaEmpregadosMobile(int NumeroIdentificacao, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdResetarContadorTabelaEmpregadosMobile", new object[] {
                        NumeroIdentificacao}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndmtdResetarContadorTabelaEmpregadosMobile(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdResetarContadorTabelaInventarioBensMobile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void mtdResetarContadorTabelaInventarioBensMobile(int NumeroIdentificacao) {
            this.Invoke("mtdResetarContadorTabelaInventarioBensMobile", new object[] {
                        NumeroIdentificacao});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdResetarContadorTabelaInventarioBensMobile(int NumeroIdentificacao, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdResetarContadorTabelaInventarioBensMobile", new object[] {
                        NumeroIdentificacao}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndmtdResetarContadorTabelaInventarioBensMobile(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getTabelaBensEletronorteMobile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getTabelaBensEletronorteMobile(string BancoDados, int Passo, int NumeroIdentificacao) {
            object[] results = this.Invoke("getTabelaBensEletronorteMobile", new object[] {
                        BancoDados,
                        Passo,
                        NumeroIdentificacao});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetTabelaBensEletronorteMobile(string BancoDados, int Passo, int NumeroIdentificacao, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getTabelaBensEletronorteMobile", new object[] {
                        BancoDados,
                        Passo,
                        NumeroIdentificacao}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetTabelaBensEletronorteMobile(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getTabelaCentroCustoMobile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getTabelaCentroCustoMobile(string BancoDados, int Passo, int NumeroIdentificacao) {
            object[] results = this.Invoke("getTabelaCentroCustoMobile", new object[] {
                        BancoDados,
                        Passo,
                        NumeroIdentificacao});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetTabelaCentroCustoMobile(string BancoDados, int Passo, int NumeroIdentificacao, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getTabelaCentroCustoMobile", new object[] {
                        BancoDados,
                        Passo,
                        NumeroIdentificacao}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetTabelaCentroCustoMobile(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getTabelaEmpregadosMobile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getTabelaEmpregadosMobile(string BancoDados, int Passo, int NumeroIdentificacao) {
            object[] results = this.Invoke("getTabelaEmpregadosMobile", new object[] {
                        BancoDados,
                        Passo,
                        NumeroIdentificacao});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetTabelaEmpregadosMobile(string BancoDados, int Passo, int NumeroIdentificacao, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getTabelaEmpregadosMobile", new object[] {
                        BancoDados,
                        Passo,
                        NumeroIdentificacao}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetTabelaEmpregadosMobile(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getTabelaInventarioBensMobile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getTabelaInventarioBensMobile(string BancoDados, int Passo, int NumeroIdentificacao) {
            object[] results = this.Invoke("getTabelaInventarioBensMobile", new object[] {
                        BancoDados,
                        Passo,
                        NumeroIdentificacao});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetTabelaInventarioBensMobile(string BancoDados, int Passo, int NumeroIdentificacao, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getTabelaInventarioBensMobile", new object[] {
                        BancoDados,
                        Passo,
                        NumeroIdentificacao}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetTabelaInventarioBensMobile(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getTabelaCentroCusto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getTabelaCentroCusto(string BancoDados) {
            object[] results = this.Invoke("getTabelaCentroCusto", new object[] {
                        BancoDados});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetTabelaCentroCusto(string BancoDados, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getTabelaCentroCusto", new object[] {
                        BancoDados}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetTabelaCentroCusto(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getTabelaBensEletronorte", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getTabelaBensEletronorte(string BancoDados) {
            object[] results = this.Invoke("getTabelaBensEletronorte", new object[] {
                        BancoDados});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetTabelaBensEletronorte(string BancoDados, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getTabelaBensEletronorte", new object[] {
                        BancoDados}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetTabelaBensEletronorte(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getTabelaEmpregados", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getTabelaEmpregados(string BancoDados) {
            object[] results = this.Invoke("getTabelaEmpregados", new object[] {
                        BancoDados});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetTabelaEmpregados(string BancoDados, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getTabelaEmpregados", new object[] {
                        BancoDados}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetTabelaEmpregados(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getTabelaInventarioBens", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getTabelaInventarioBens(string BancoDados) {
            object[] results = this.Invoke("getTabelaInventarioBens", new object[] {
                        BancoDados});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetTabelaInventarioBens(string BancoDados, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getTabelaInventarioBens", new object[] {
                        BancoDados}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetTabelaInventarioBens(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setTabelaInventarioBens", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setTabelaInventarioBens(string BancoDados, System.Data.DataSet AjustadorDados, int NumeroIdentificacao) {
            this.Invoke("setTabelaInventarioBens", new object[] {
                        BancoDados,
                        AjustadorDados,
                        NumeroIdentificacao});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetTabelaInventarioBens(string BancoDados, System.Data.DataSet AjustadorDados, int NumeroIdentificacao, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setTabelaInventarioBens", new object[] {
                        BancoDados,
                        AjustadorDados,
                        NumeroIdentificacao}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndsetTabelaInventarioBens(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/prpTabelaInventarioBens", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet prpTabelaInventarioBens(string BancoDados, System.Data.DataSet AjustadorDados, int NumeroIdentificacao) {
            object[] results = this.Invoke("prpTabelaInventarioBens", new object[] {
                        BancoDados,
                        AjustadorDados,
                        NumeroIdentificacao});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginprpTabelaInventarioBens(string BancoDados, System.Data.DataSet AjustadorDados, int NumeroIdentificacao, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("prpTabelaInventarioBens", new object[] {
                        BancoDados,
                        AjustadorDados,
                        NumeroIdentificacao}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndprpTabelaInventarioBens(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdUploadArquivo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool mtdUploadArquivo([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] f, string NomeArquivo) {
            object[] results = this.Invoke("mtdUploadArquivo", new object[] {
                        f,
                        NomeArquivo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdUploadArquivo(byte[] f, string NomeArquivo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdUploadArquivo", new object[] {
                        f,
                        NomeArquivo}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndmtdUploadArquivo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdObterDataTempoSistemaAtual", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime mtdObterDataTempoSistemaAtual() {
            object[] results = this.Invoke("mtdObterDataTempoSistemaAtual", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdObterDataTempoSistemaAtual(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdObterDataTempoSistemaAtual", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.DateTime EndmtdObterDataTempoSistemaAtual(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdObterDataTempoSistemaUtc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime mtdObterDataTempoSistemaUtc() {
            object[] results = this.Invoke("mtdObterDataTempoSistemaUtc", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdObterDataTempoSistemaUtc(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdObterDataTempoSistemaUtc", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.DateTime EndmtdObterDataTempoSistemaUtc(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdCalcularCodigoEspalhamentoTotal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long mtdCalcularCodigoEspalhamentoTotal(string BancoDados, string Tabela, string CampoSelecionador) {
            object[] results = this.Invoke("mtdCalcularCodigoEspalhamentoTotal", new object[] {
                        BancoDados,
                        Tabela,
                        CampoSelecionador});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdCalcularCodigoEspalhamentoTotal(string BancoDados, string Tabela, string CampoSelecionador, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdCalcularCodigoEspalhamentoTotal", new object[] {
                        BancoDados,
                        Tabela,
                        CampoSelecionador}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndmtdCalcularCodigoEspalhamentoTotal(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdCalcularCodigoEspalhamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long mtdCalcularCodigoEspalhamento(string BancoDados, string Tabela, string CampoSelecionador, object Dado) {
            object[] results = this.Invoke("mtdCalcularCodigoEspalhamento", new object[] {
                        BancoDados,
                        Tabela,
                        CampoSelecionador,
                        Dado});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdCalcularCodigoEspalhamento(string BancoDados, string Tabela, string CampoSelecionador, object Dado, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdCalcularCodigoEspalhamento", new object[] {
                        BancoDados,
                        Tabela,
                        CampoSelecionador,
                        Dado}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndmtdCalcularCodigoEspalhamento(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdCalcularCodigoEspalhamentoTabelaInventarioBensTotal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long mtdCalcularCodigoEspalhamentoTabelaInventarioBensTotal(string BancoDados) {
            object[] results = this.Invoke("mtdCalcularCodigoEspalhamentoTabelaInventarioBensTotal", new object[] {
                        BancoDados});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdCalcularCodigoEspalhamentoTabelaInventarioBensTotal(string BancoDados, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdCalcularCodigoEspalhamentoTabelaInventarioBensTotal", new object[] {
                        BancoDados}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndmtdCalcularCodigoEspalhamentoTabelaInventarioBensTotal(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdCalcularCodigoEspalhamentoTabelaInventarioBens", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long mtdCalcularCodigoEspalhamentoTabelaInventarioBens(string BancoDados, string CampoSelecionador, object Dado) {
            object[] results = this.Invoke("mtdCalcularCodigoEspalhamentoTabelaInventarioBens", new object[] {
                        BancoDados,
                        CampoSelecionador,
                        Dado});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdCalcularCodigoEspalhamentoTabelaInventarioBens(string BancoDados, string CampoSelecionador, object Dado, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdCalcularCodigoEspalhamentoTabelaInventarioBens", new object[] {
                        BancoDados,
                        CampoSelecionador,
                        Dado}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndmtdCalcularCodigoEspalhamentoTabelaInventarioBens(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdCalcularCodigoEspalhamentoAjustadorDados", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long mtdCalcularCodigoEspalhamentoAjustadorDados(System.Data.DataSet AjustadorDados) {
            object[] results = this.Invoke("mtdCalcularCodigoEspalhamentoAjustadorDados", new object[] {
                        AjustadorDados});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdCalcularCodigoEspalhamentoAjustadorDados(System.Data.DataSet AjustadorDados, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdCalcularCodigoEspalhamentoAjustadorDados", new object[] {
                        AjustadorDados}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndmtdCalcularCodigoEspalhamentoAjustadorDados(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdCalcularCodigoEspalhamentoAjustadorDadosLinha", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long mtdCalcularCodigoEspalhamentoAjustadorDadosLinha(System.Data.DataSet AjustadorDados, int linha) {
            object[] results = this.Invoke("mtdCalcularCodigoEspalhamentoAjustadorDadosLinha", new object[] {
                        AjustadorDados,
                        linha});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdCalcularCodigoEspalhamentoAjustadorDadosLinha(System.Data.DataSet AjustadorDados, int linha, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdCalcularCodigoEspalhamentoAjustadorDadosLinha", new object[] {
                        AjustadorDados,
                        linha}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndmtdCalcularCodigoEspalhamentoAjustadorDadosLinha(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdCalcularCodigoEspalhamentoAjustadorDadosTabelaInventarioBen" +
            "sLinha", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long mtdCalcularCodigoEspalhamentoAjustadorDadosTabelaInventarioBensLinha(System.Data.DataSet AjustadorDados, int linha) {
            object[] results = this.Invoke("mtdCalcularCodigoEspalhamentoAjustadorDadosTabelaInventarioBensLinha", new object[] {
                        AjustadorDados,
                        linha});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdCalcularCodigoEspalhamentoAjustadorDadosTabelaInventarioBensLinha(System.Data.DataSet AjustadorDados, int linha, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdCalcularCodigoEspalhamentoAjustadorDadosTabelaInventarioBensLinha", new object[] {
                        AjustadorDados,
                        linha}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndmtdCalcularCodigoEspalhamentoAjustadorDadosTabelaInventarioBensLinha(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdObterNumeroColunas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long mtdObterNumeroColunas(string BancoDados, string Tabela, string CampoSelecionador, object Dado) {
            object[] results = this.Invoke("mtdObterNumeroColunas", new object[] {
                        BancoDados,
                        Tabela,
                        CampoSelecionador,
                        Dado});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdObterNumeroColunas(string BancoDados, string Tabela, string CampoSelecionador, object Dado, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdObterNumeroColunas", new object[] {
                        BancoDados,
                        Tabela,
                        CampoSelecionador,
                        Dado}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndmtdObterNumeroColunas(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdObterNumeroLinhas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long mtdObterNumeroLinhas(string BancoDados, string Tabela, string CampoSelecionador, object Dado) {
            object[] results = this.Invoke("mtdObterNumeroLinhas", new object[] {
                        BancoDados,
                        Tabela,
                        CampoSelecionador,
                        Dado});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdObterNumeroLinhas(string BancoDados, string Tabela, string CampoSelecionador, object Dado, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdObterNumeroLinhas", new object[] {
                        BancoDados,
                        Tabela,
                        CampoSelecionador,
                        Dado}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndmtdObterNumeroLinhas(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdObterNumeroColunasAjustadorDados", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int mtdObterNumeroColunasAjustadorDados(System.Data.DataSet AjustadorDados) {
            object[] results = this.Invoke("mtdObterNumeroColunasAjustadorDados", new object[] {
                        AjustadorDados});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdObterNumeroColunasAjustadorDados(System.Data.DataSet AjustadorDados, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdObterNumeroColunasAjustadorDados", new object[] {
                        AjustadorDados}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndmtdObterNumeroColunasAjustadorDados(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdObterNumeroLinhasAjustadorDados", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int mtdObterNumeroLinhasAjustadorDados(System.Data.DataSet AjustadorDados) {
            object[] results = this.Invoke("mtdObterNumeroLinhasAjustadorDados", new object[] {
                        AjustadorDados});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdObterNumeroLinhasAjustadorDados(System.Data.DataSet AjustadorDados, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdObterNumeroLinhasAjustadorDados", new object[] {
                        AjustadorDados}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndmtdObterNumeroLinhasAjustadorDados(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdObterNumeroLinhasAjustadorDadosTabela", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int mtdObterNumeroLinhasAjustadorDadosTabela(System.Data.DataSet AjustadorDados, int Tabela) {
            object[] results = this.Invoke("mtdObterNumeroLinhasAjustadorDadosTabela", new object[] {
                        AjustadorDados,
                        Tabela});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdObterNumeroLinhasAjustadorDadosTabela(System.Data.DataSet AjustadorDados, int Tabela, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdObterNumeroLinhasAjustadorDadosTabela", new object[] {
                        AjustadorDados,
                        Tabela}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndmtdObterNumeroLinhasAjustadorDadosTabela(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdTestarConexaoAbertaBancoDados", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool mtdTestarConexaoAbertaBancoDados(string BancoDados) {
            object[] results = this.Invoke("mtdTestarConexaoAbertaBancoDados", new object[] {
                        BancoDados});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdTestarConexaoAbertaBancoDados(string BancoDados, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdTestarConexaoAbertaBancoDados", new object[] {
                        BancoDados}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndmtdTestarConexaoAbertaBancoDados(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdTestarExecucaoComandoBancoDados", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool mtdTestarExecucaoComandoBancoDados(string BancoDados, string Tabela) {
            object[] results = this.Invoke("mtdTestarExecucaoComandoBancoDados", new object[] {
                        BancoDados,
                        Tabela});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdTestarExecucaoComandoBancoDados(string BancoDados, string Tabela, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdTestarExecucaoComandoBancoDados", new object[] {
                        BancoDados,
                        Tabela}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndmtdTestarExecucaoComandoBancoDados(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdResetarConfiguracoes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void mtdResetarConfiguracoes() {
            this.Invoke("mtdResetarConfiguracoes", new object[0]);
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdResetarConfiguracoes(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdResetarConfiguracoes", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public void EndmtdResetarConfiguracoes(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdIniciarCriacaoTabelas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void mtdIniciarCriacaoTabelas() {
            this.Invoke("mtdIniciarCriacaoTabelas", new object[0]);
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdIniciarCriacaoTabelas(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdIniciarCriacaoTabelas", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public void EndmtdIniciarCriacaoTabelas(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdObterLinhaTabelaInventarioBens", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int mtdObterLinhaTabelaInventarioBens(int NumeroIdentificacao) {
            object[] results = this.Invoke("mtdObterLinhaTabelaInventarioBens", new object[] {
                        NumeroIdentificacao});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdObterLinhaTabelaInventarioBens(int NumeroIdentificacao, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdObterLinhaTabelaInventarioBens", new object[] {
                        NumeroIdentificacao}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndmtdObterLinhaTabelaInventarioBens(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdObterLinhaTotalTabelaInventarioBens", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int mtdObterLinhaTotalTabelaInventarioBens(int NumeroIdentificacao) {
            object[] results = this.Invoke("mtdObterLinhaTotalTabelaInventarioBens", new object[] {
                        NumeroIdentificacao});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdObterLinhaTotalTabelaInventarioBens(int NumeroIdentificacao, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdObterLinhaTotalTabelaInventarioBens", new object[] {
                        NumeroIdentificacao}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndmtdObterLinhaTotalTabelaInventarioBens(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdObterLinhaAcumuladoTotalTabelaInventarioBens", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int mtdObterLinhaAcumuladoTotalTabelaInventarioBens(int NumeroIdentificacao) {
            object[] results = this.Invoke("mtdObterLinhaAcumuladoTotalTabelaInventarioBens", new object[] {
                        NumeroIdentificacao});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdObterLinhaAcumuladoTotalTabelaInventarioBens(int NumeroIdentificacao, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdObterLinhaAcumuladoTotalTabelaInventarioBens", new object[] {
                        NumeroIdentificacao}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndmtdObterLinhaAcumuladoTotalTabelaInventarioBens(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdObterNumeroItensInseridos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int mtdObterNumeroItensInseridos(int NumeroIdentificacao) {
            object[] results = this.Invoke("mtdObterNumeroItensInseridos", new object[] {
                        NumeroIdentificacao});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdObterNumeroItensInseridos(int NumeroIdentificacao, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdObterNumeroItensInseridos", new object[] {
                        NumeroIdentificacao}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndmtdObterNumeroItensInseridos(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdObterNumeroItensAtualizados", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int mtdObterNumeroItensAtualizados(int NumeroIdentificacao) {
            object[] results = this.Invoke("mtdObterNumeroItensAtualizados", new object[] {
                        NumeroIdentificacao});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdObterNumeroItensAtualizados(int NumeroIdentificacao, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdObterNumeroItensAtualizados", new object[] {
                        NumeroIdentificacao}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndmtdObterNumeroItensAtualizados(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdObterNumeroItensInalterados", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int mtdObterNumeroItensInalterados(int NumeroIdentificacao) {
            object[] results = this.Invoke("mtdObterNumeroItensInalterados", new object[] {
                        NumeroIdentificacao});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdObterNumeroItensInalterados(int NumeroIdentificacao, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdObterNumeroItensInalterados", new object[] {
                        NumeroIdentificacao}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndmtdObterNumeroItensInalterados(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdResetarContadorLinhaAcumuladoTotalTabelaInventarioBens", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void mtdResetarContadorLinhaAcumuladoTotalTabelaInventarioBens(int NumeroIdentificacao) {
            this.Invoke("mtdResetarContadorLinhaAcumuladoTotalTabelaInventarioBens", new object[] {
                        NumeroIdentificacao});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdResetarContadorLinhaAcumuladoTotalTabelaInventarioBens(int NumeroIdentificacao, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdResetarContadorLinhaAcumuladoTotalTabelaInventarioBens", new object[] {
                        NumeroIdentificacao}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndmtdResetarContadorLinhaAcumuladoTotalTabelaInventarioBens(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdResetarGerarProximoNumeroCodigoOtimizado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void mtdResetarGerarProximoNumeroCodigoOtimizado() {
            this.Invoke("mtdResetarGerarProximoNumeroCodigoOtimizado", new object[0]);
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdResetarGerarProximoNumeroCodigoOtimizado(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdResetarGerarProximoNumeroCodigoOtimizado", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public void EndmtdResetarGerarProximoNumeroCodigoOtimizado(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdManterCanalAberto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool mtdManterCanalAberto(int NumeroIdentificacao) {
            object[] results = this.Invoke("mtdManterCanalAberto", new object[] {
                        NumeroIdentificacao});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdManterCanalAberto(int NumeroIdentificacao, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdManterCanalAberto", new object[] {
                        NumeroIdentificacao}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndmtdManterCanalAberto(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdFecharCanal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void mtdFecharCanal(int NumeroIdentificacao) {
            this.Invoke("mtdFecharCanal", new object[] {
                        NumeroIdentificacao});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdFecharCanal(int NumeroIdentificacao, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdFecharCanal", new object[] {
                        NumeroIdentificacao}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndmtdFecharCanal(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdFecharTodosCanais", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void mtdFecharTodosCanais() {
            this.Invoke("mtdFecharTodosCanais", new object[0]);
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdFecharTodosCanais(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdFecharTodosCanais", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public void EndmtdFecharTodosCanais(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdForcarParadagetTabelaBensEletronorteMobile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void mtdForcarParadagetTabelaBensEletronorteMobile(int NumeroIdentificacao) {
            this.Invoke("mtdForcarParadagetTabelaBensEletronorteMobile", new object[] {
                        NumeroIdentificacao});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdForcarParadagetTabelaBensEletronorteMobile(int NumeroIdentificacao, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdForcarParadagetTabelaBensEletronorteMobile", new object[] {
                        NumeroIdentificacao}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndmtdForcarParadagetTabelaBensEletronorteMobile(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdForcarParadagetTabelaCentroCustoMobile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void mtdForcarParadagetTabelaCentroCustoMobile(int NumeroIdentificacao) {
            this.Invoke("mtdForcarParadagetTabelaCentroCustoMobile", new object[] {
                        NumeroIdentificacao});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdForcarParadagetTabelaCentroCustoMobile(int NumeroIdentificacao, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdForcarParadagetTabelaCentroCustoMobile", new object[] {
                        NumeroIdentificacao}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndmtdForcarParadagetTabelaCentroCustoMobile(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdForcarParadagetTabelaEmpregadosMobile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void mtdForcarParadagetTabelaEmpregadosMobile(int NumeroIdentificacao) {
            this.Invoke("mtdForcarParadagetTabelaEmpregadosMobile", new object[] {
                        NumeroIdentificacao});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdForcarParadagetTabelaEmpregadosMobile(int NumeroIdentificacao, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdForcarParadagetTabelaEmpregadosMobile", new object[] {
                        NumeroIdentificacao}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndmtdForcarParadagetTabelaEmpregadosMobile(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdForcarParadagetTabelaInventarioBensMobile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void mtdForcarParadagetTabelaInventarioBensMobile(int NumeroIdentificacao) {
            this.Invoke("mtdForcarParadagetTabelaInventarioBensMobile", new object[] {
                        NumeroIdentificacao});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdForcarParadagetTabelaInventarioBensMobile(int NumeroIdentificacao, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdForcarParadagetTabelaInventarioBensMobile", new object[] {
                        NumeroIdentificacao}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndmtdForcarParadagetTabelaInventarioBensMobile(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdForcarParadasetTabelaInventarioBens", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void mtdForcarParadasetTabelaInventarioBens(int NumeroIdentificacao) {
            this.Invoke("mtdForcarParadasetTabelaInventarioBens", new object[] {
                        NumeroIdentificacao});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdForcarParadasetTabelaInventarioBens(int NumeroIdentificacao, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdForcarParadasetTabelaInventarioBens", new object[] {
                        NumeroIdentificacao}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndmtdForcarParadasetTabelaInventarioBens(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
    }
}
