//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9179
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.9179.
// 
namespace prjInspecaoCSNet35.WebServiceInspecao {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceInspecaoSoap", Namespace="http://tempuri.org/")]
    public partial class WebServiceInspecao : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public WebServiceInspecao() {
            this.Url = "http://localhost:61062/Todos/WebServiceInspecao.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndHelloWorld(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdObterDadosTabelaInspecao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet mtdObterDadosTabelaInspecao() {
            object[] results = this.Invoke("mtdObterDadosTabelaInspecao", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdObterDadosTabelaInspecao(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdObterDadosTabelaInspecao", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndmtdObterDadosTabelaInspecao(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdObterDadosTabelaEstatistica_01", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet mtdObterDadosTabelaEstatistica_01() {
            object[] results = this.Invoke("mtdObterDadosTabelaEstatistica_01", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdObterDadosTabelaEstatistica_01(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdObterDadosTabelaEstatistica_01", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndmtdObterDadosTabelaEstatistica_01(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdObterDadosTabelaEstatistica_02", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet mtdObterDadosTabelaEstatistica_02() {
            object[] results = this.Invoke("mtdObterDadosTabelaEstatistica_02", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdObterDadosTabelaEstatistica_02(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdObterDadosTabelaEstatistica_02", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndmtdObterDadosTabelaEstatistica_02(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdInserirDadosTabelaInspecao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool mtdInserirDadosTabelaInspecao(System.Data.DataSet Ds) {
            object[] results = this.Invoke("mtdInserirDadosTabelaInspecao", new object[] {
                        Ds});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdInserirDadosTabelaInspecao(System.Data.DataSet Ds, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdInserirDadosTabelaInspecao", new object[] {
                        Ds}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndmtdInserirDadosTabelaInspecao(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdObterDadosTabelaEndereco", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet mtdObterDadosTabelaEndereco() {
            object[] results = this.Invoke("mtdObterDadosTabelaEndereco", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdObterDadosTabelaEndereco(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdObterDadosTabelaEndereco", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndmtdObterDadosTabelaEndereco(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdObterDataTempoSistemaAtual", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime mtdObterDataTempoSistemaAtual() {
            object[] results = this.Invoke("mtdObterDataTempoSistemaAtual", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdObterDataTempoSistemaAtual(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdObterDataTempoSistemaAtual", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.DateTime EndmtdObterDataTempoSistemaAtual(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdObterDataTempoSistemaUtc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime mtdObterDataTempoSistemaUtc() {
            object[] results = this.Invoke("mtdObterDataTempoSistemaUtc", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmtdObterDataTempoSistemaUtc(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("mtdObterDataTempoSistemaUtc", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.DateTime EndmtdObterDataTempoSistemaUtc(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.DateTime)(results[0]));
        }
    }
}
