//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace prjInspecaoCSNet40.WebServiceInspecao {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceInspecaoSoap", Namespace="http://tempuri.org/")]
    public partial class WebServiceInspecao : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback mtdObterDadosTabelaInspecaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback mtdObterDadosTabelaEstatistica_01OperationCompleted;
        
        private System.Threading.SendOrPostCallback mtdObterDadosTabelaEstatistica_02OperationCompleted;
        
        private System.Threading.SendOrPostCallback mtdInserirDadosTabelaInspecaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback mtdObterDadosTabelaEnderecoOperationCompleted;
        
        private System.Threading.SendOrPostCallback mtdObterDataTempoSistemaAtualOperationCompleted;
        
        private System.Threading.SendOrPostCallback mtdObterDataTempoSistemaUtcOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServiceInspecao() {
            this.Url = global::prjInspecaoCSNet40.Properties.Settings.Default.prjInspecaoCSNet40_WebServiceInspecao_WebServiceInspecao;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event mtdObterDadosTabelaInspecaoCompletedEventHandler mtdObterDadosTabelaInspecaoCompleted;
        
        /// <remarks/>
        public event mtdObterDadosTabelaEstatistica_01CompletedEventHandler mtdObterDadosTabelaEstatistica_01Completed;
        
        /// <remarks/>
        public event mtdObterDadosTabelaEstatistica_02CompletedEventHandler mtdObterDadosTabelaEstatistica_02Completed;
        
        /// <remarks/>
        public event mtdInserirDadosTabelaInspecaoCompletedEventHandler mtdInserirDadosTabelaInspecaoCompleted;
        
        /// <remarks/>
        public event mtdObterDadosTabelaEnderecoCompletedEventHandler mtdObterDadosTabelaEnderecoCompleted;
        
        /// <remarks/>
        public event mtdObterDataTempoSistemaAtualCompletedEventHandler mtdObterDataTempoSistemaAtualCompleted;
        
        /// <remarks/>
        public event mtdObterDataTempoSistemaUtcCompletedEventHandler mtdObterDataTempoSistemaUtcCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdObterDadosTabelaInspecao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet mtdObterDadosTabelaInspecao() {
            object[] results = this.Invoke("mtdObterDadosTabelaInspecao", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void mtdObterDadosTabelaInspecaoAsync() {
            this.mtdObterDadosTabelaInspecaoAsync(null);
        }
        
        /// <remarks/>
        public void mtdObterDadosTabelaInspecaoAsync(object userState) {
            if ((this.mtdObterDadosTabelaInspecaoOperationCompleted == null)) {
                this.mtdObterDadosTabelaInspecaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmtdObterDadosTabelaInspecaoOperationCompleted);
            }
            this.InvokeAsync("mtdObterDadosTabelaInspecao", new object[0], this.mtdObterDadosTabelaInspecaoOperationCompleted, userState);
        }
        
        private void OnmtdObterDadosTabelaInspecaoOperationCompleted(object arg) {
            if ((this.mtdObterDadosTabelaInspecaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mtdObterDadosTabelaInspecaoCompleted(this, new mtdObterDadosTabelaInspecaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdObterDadosTabelaEstatistica_01", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet mtdObterDadosTabelaEstatistica_01() {
            object[] results = this.Invoke("mtdObterDadosTabelaEstatistica_01", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void mtdObterDadosTabelaEstatistica_01Async() {
            this.mtdObterDadosTabelaEstatistica_01Async(null);
        }
        
        /// <remarks/>
        public void mtdObterDadosTabelaEstatistica_01Async(object userState) {
            if ((this.mtdObterDadosTabelaEstatistica_01OperationCompleted == null)) {
                this.mtdObterDadosTabelaEstatistica_01OperationCompleted = new System.Threading.SendOrPostCallback(this.OnmtdObterDadosTabelaEstatistica_01OperationCompleted);
            }
            this.InvokeAsync("mtdObterDadosTabelaEstatistica_01", new object[0], this.mtdObterDadosTabelaEstatistica_01OperationCompleted, userState);
        }
        
        private void OnmtdObterDadosTabelaEstatistica_01OperationCompleted(object arg) {
            if ((this.mtdObterDadosTabelaEstatistica_01Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mtdObterDadosTabelaEstatistica_01Completed(this, new mtdObterDadosTabelaEstatistica_01CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdObterDadosTabelaEstatistica_02", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet mtdObterDadosTabelaEstatistica_02() {
            object[] results = this.Invoke("mtdObterDadosTabelaEstatistica_02", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void mtdObterDadosTabelaEstatistica_02Async() {
            this.mtdObterDadosTabelaEstatistica_02Async(null);
        }
        
        /// <remarks/>
        public void mtdObterDadosTabelaEstatistica_02Async(object userState) {
            if ((this.mtdObterDadosTabelaEstatistica_02OperationCompleted == null)) {
                this.mtdObterDadosTabelaEstatistica_02OperationCompleted = new System.Threading.SendOrPostCallback(this.OnmtdObterDadosTabelaEstatistica_02OperationCompleted);
            }
            this.InvokeAsync("mtdObterDadosTabelaEstatistica_02", new object[0], this.mtdObterDadosTabelaEstatistica_02OperationCompleted, userState);
        }
        
        private void OnmtdObterDadosTabelaEstatistica_02OperationCompleted(object arg) {
            if ((this.mtdObterDadosTabelaEstatistica_02Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mtdObterDadosTabelaEstatistica_02Completed(this, new mtdObterDadosTabelaEstatistica_02CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdInserirDadosTabelaInspecao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool mtdInserirDadosTabelaInspecao(System.Data.DataSet Ds) {
            object[] results = this.Invoke("mtdInserirDadosTabelaInspecao", new object[] {
                        Ds});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void mtdInserirDadosTabelaInspecaoAsync(System.Data.DataSet Ds) {
            this.mtdInserirDadosTabelaInspecaoAsync(Ds, null);
        }
        
        /// <remarks/>
        public void mtdInserirDadosTabelaInspecaoAsync(System.Data.DataSet Ds, object userState) {
            if ((this.mtdInserirDadosTabelaInspecaoOperationCompleted == null)) {
                this.mtdInserirDadosTabelaInspecaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmtdInserirDadosTabelaInspecaoOperationCompleted);
            }
            this.InvokeAsync("mtdInserirDadosTabelaInspecao", new object[] {
                        Ds}, this.mtdInserirDadosTabelaInspecaoOperationCompleted, userState);
        }
        
        private void OnmtdInserirDadosTabelaInspecaoOperationCompleted(object arg) {
            if ((this.mtdInserirDadosTabelaInspecaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mtdInserirDadosTabelaInspecaoCompleted(this, new mtdInserirDadosTabelaInspecaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdObterDadosTabelaEndereco", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet mtdObterDadosTabelaEndereco() {
            object[] results = this.Invoke("mtdObterDadosTabelaEndereco", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void mtdObterDadosTabelaEnderecoAsync() {
            this.mtdObterDadosTabelaEnderecoAsync(null);
        }
        
        /// <remarks/>
        public void mtdObterDadosTabelaEnderecoAsync(object userState) {
            if ((this.mtdObterDadosTabelaEnderecoOperationCompleted == null)) {
                this.mtdObterDadosTabelaEnderecoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmtdObterDadosTabelaEnderecoOperationCompleted);
            }
            this.InvokeAsync("mtdObterDadosTabelaEndereco", new object[0], this.mtdObterDadosTabelaEnderecoOperationCompleted, userState);
        }
        
        private void OnmtdObterDadosTabelaEnderecoOperationCompleted(object arg) {
            if ((this.mtdObterDadosTabelaEnderecoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mtdObterDadosTabelaEnderecoCompleted(this, new mtdObterDadosTabelaEnderecoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdObterDataTempoSistemaAtual", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime mtdObterDataTempoSistemaAtual() {
            object[] results = this.Invoke("mtdObterDataTempoSistemaAtual", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void mtdObterDataTempoSistemaAtualAsync() {
            this.mtdObterDataTempoSistemaAtualAsync(null);
        }
        
        /// <remarks/>
        public void mtdObterDataTempoSistemaAtualAsync(object userState) {
            if ((this.mtdObterDataTempoSistemaAtualOperationCompleted == null)) {
                this.mtdObterDataTempoSistemaAtualOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmtdObterDataTempoSistemaAtualOperationCompleted);
            }
            this.InvokeAsync("mtdObterDataTempoSistemaAtual", new object[0], this.mtdObterDataTempoSistemaAtualOperationCompleted, userState);
        }
        
        private void OnmtdObterDataTempoSistemaAtualOperationCompleted(object arg) {
            if ((this.mtdObterDataTempoSistemaAtualCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mtdObterDataTempoSistemaAtualCompleted(this, new mtdObterDataTempoSistemaAtualCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mtdObterDataTempoSistemaUtc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime mtdObterDataTempoSistemaUtc() {
            object[] results = this.Invoke("mtdObterDataTempoSistemaUtc", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void mtdObterDataTempoSistemaUtcAsync() {
            this.mtdObterDataTempoSistemaUtcAsync(null);
        }
        
        /// <remarks/>
        public void mtdObterDataTempoSistemaUtcAsync(object userState) {
            if ((this.mtdObterDataTempoSistemaUtcOperationCompleted == null)) {
                this.mtdObterDataTempoSistemaUtcOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmtdObterDataTempoSistemaUtcOperationCompleted);
            }
            this.InvokeAsync("mtdObterDataTempoSistemaUtc", new object[0], this.mtdObterDataTempoSistemaUtcOperationCompleted, userState);
        }
        
        private void OnmtdObterDataTempoSistemaUtcOperationCompleted(object arg) {
            if ((this.mtdObterDataTempoSistemaUtcCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mtdObterDataTempoSistemaUtcCompleted(this, new mtdObterDataTempoSistemaUtcCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void mtdObterDadosTabelaInspecaoCompletedEventHandler(object sender, mtdObterDadosTabelaInspecaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mtdObterDadosTabelaInspecaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mtdObterDadosTabelaInspecaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void mtdObterDadosTabelaEstatistica_01CompletedEventHandler(object sender, mtdObterDadosTabelaEstatistica_01CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mtdObterDadosTabelaEstatistica_01CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mtdObterDadosTabelaEstatistica_01CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void mtdObterDadosTabelaEstatistica_02CompletedEventHandler(object sender, mtdObterDadosTabelaEstatistica_02CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mtdObterDadosTabelaEstatistica_02CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mtdObterDadosTabelaEstatistica_02CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void mtdInserirDadosTabelaInspecaoCompletedEventHandler(object sender, mtdInserirDadosTabelaInspecaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mtdInserirDadosTabelaInspecaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mtdInserirDadosTabelaInspecaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void mtdObterDadosTabelaEnderecoCompletedEventHandler(object sender, mtdObterDadosTabelaEnderecoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mtdObterDadosTabelaEnderecoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mtdObterDadosTabelaEnderecoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void mtdObterDataTempoSistemaAtualCompletedEventHandler(object sender, mtdObterDataTempoSistemaAtualCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mtdObterDataTempoSistemaAtualCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mtdObterDataTempoSistemaAtualCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void mtdObterDataTempoSistemaUtcCompletedEventHandler(object sender, mtdObterDataTempoSistemaUtcCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mtdObterDataTempoSistemaUtcCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mtdObterDataTempoSistemaUtcCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591